### ISSUE TITLE
  Serverless plugin "serverless-offline-sns" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

### ISSUE THREAD

**Issue by eladhaz05** [mj1618/serverless-offline-sns#1]
I got this error every time I try to start sls offline.
I add it to the plugins and install it.
Why?

Thanks.

**Comment by mj1618** [comment]
Hi eladhaz05!

Thanks for your bug submission, I can take a look for you.

Which commands did you run and what is your serverless.yml?

Cheers
Matt

**Comment by mj1618** [comment]
Hi @eladhaz05 !

There was one missing dependency in the plugin - `node-fetch`.

I have fixed this and published a latest version - 0.12.0.

Please update and you should see it fixed.

I have also done an example application to show how the config ties together - https://github.com/mj1618/serverless-offline-sns-example

**Comment by eladhaz05** [comment]
Thank you.
But I have another issue.
If I send sns.publish({
                    Message: JSON.stringify({test:test}),
                    MessageStructure: "json",
                    TopicArn:'arn:aws:sns:eu-west-1:254002648520:Heimdallr-Invoke'
                  }
I never get the data in the lambda.
When I changed in the sns-server.js file line 162 : 
return node_fetch_1.default(sub.Endpoint, { method: "POST", body: message })
                .then(function (res) { return _this.debug(res); });
to 
return node_fetch_1.default(sub.Endpoint, { method: "POST", body: message, header:application/json })
                .then(function (res) { return _this.debug(res); });
i get the data.
Can you fix it?
Thank you

**Comment by mj1618** [comment]
Awesome @eladhaz05 thanks for your help on finding these bugs.

I have now pushed `v0.13.0`.

I'll be continuing to look for bugs this week, if you find any more let me know 🙂

**Comment by mj1618** [comment]
Hi @eladhaz05 

I have just committed a change in `0.14.0` to use the correct Lambda SNS event message structure according to [Sample Events](http://docs.aws.amazon.com/lambda/latest/dg/eventsources.html)

I've updated the [example](https://github.com/mj1618/serverless-offline-sns-example) to demonstrate this.

**Comment by mj1618** [comment]
Seems it is fixed for me, I hope it also has fixed your issue @eladhaz05 so I'm going to close this ticket.

If you find any other issues feel free to create a new issue.
