### ISSUE TITLE
how to stop automatic unsubscribeAll?

### ISSUE THREAD

**Issue by chichicuervo** [mj1618/serverless-offline-sns#115]
My application is designed in a master/slave format, with each component being it's own Serverless/Cloudformation deploy.  The basic jist is the master component sends each slave component instructions via SNS, which means /both/ the master and /each/ slave component needs to talk to the same SNS queues.

I've got a localstack going in it's own VM and I've gotten each half of the application talking to it just fine, however when bringing up both halves at the same time (on different VMs), the 2nd one to init automatically unsubscribes the first half's SNS subscriptions.

Looking thru the code, I'm seeing a call to unsubscribeAll() within the subscribeAll() function.  Is there an alternative way to configure this plugin to allow normal cross-project SNS or am I going to have to fork and hack at it?

**Comment by chichicuervo** [comment]
seems to be related to #53

**Comment by mj1618** [comment]
I think this should be fixed now
