### ISSUE TITLE
Lambda function is not invoked when displayName is used in SNS in yml

### ISSUE THREAD

**Issue by jadehwangsonos** [mj1618/serverless-offline-sns#13]
Hi, 
I thought this would have been resolved by the issue 'Does not pick up SNS queues defined with display name in YML #10' but I still have the issue with the version 0.25.0. 

This is from your example:

Works in serverless.yml: 
  pong:
    handler: handler.pong
    events:
      - sns: test-topic

NOT Work in serverless.yml:

  pong:
    handler: handler.pong
    events:
      - sns:
          topicName: test-topic

The lambda function pong (with topicName) is not invoked when ping function publishes to SNS . Shouldn't this be supported?

**Comment by mj1618** [comment]
Hi @jadehwangsonos !

Sorry about this, there has been a fix since then and that is in v0.27.0

Can you please try this and let me know if it works for you?

Thank you for the bug report.

Matt

**Comment by mj1618** [comment]
Aha - one issue I've found is if you have 2 spaces before topicName it considers topicName part of the events object in yaml.

You need 3 spaces more than sns to consider it an item in SNS.

To clarify I've added this to the example project here: https://github.com/mj1618/serverless-offline-sns-example/blob/master/serverless.yml#L13

Let me know how you go 🙂

**Comment by jadehwangsonos** [comment]
I downloaded v0.27.0 and it works! I had enough spaces for an item in SNS but it got lost while I'm writing a comment on Github.
Thanks for your quick feedback!

**Comment by mj1618** [comment]
No problem! Thanks for reporting the problem
