### ISSUE TITLE
localhost in TopicArn does not work

### ISSUE THREAD

**Issue by jadehwangsonos** [mj1618/serverless-offline-sns#14]
Hi, 

I found that the lambda function subscribing offline-sns works well if TopicArn uses us-east-1 for region but does not work for localhost. Since offline-sns meant work locally, I think localhost should work. What do you think?

The following is the example from serverless-offline-sns-example.

**[What works]**
  sns.publish({
    Message: "hello!",
    MessageStructure: "json",
    TopicArn: "arn:aws:sns:**us-east-1**:123456789012:test-topic",
  }

**[What not work]**
  sns.publish({
    Message: "hello!",
    MessageStructure: "json",
    TopicArn: "arn:aws:sns:**localhost**:123456789012:test-topic",
  }

Thanks!

**Comment by mj1618** [comment]
Hi there!

Thanks again for an interesting report.

I’ll have a look, but I think the SNS library only accepts legitimate AWS regions.

The pattern I’ve used in the past is to always keep the same region you’re deploying to.

If it doesn’t work with say eu-West-1 I will definitely want to fix that. It could be the same fix for both.

**Comment by jadehwangsonos** [comment]
I was thinking the use case like setting AWS_REGION in local in env.yml. Then use it for offline-sns and local Dynamo and so on for local testing.

**Comment by mj1618** [comment]
Yea I'm not sure if that's a recommended approach. I will take a look now

**Comment by mj1618** [comment]
Ok I've just published 0.28.

If you set your region in serverless.yml, the SNS listener will also use that region. This includes localhost.

See here for an example - https://github.com/mj1618/serverless-offline-sns-example/tree/arbitrary-regions

It originally didn't allow any non-us-east region so it was worth fixing.

**Comment by jadehwangsonos** [comment]
It works as a charm. Thank you so much for your support!
