### ISSUE TITLE
SNS Offline + Typescript

### ISSUE THREAD

**Issue by Bemjamin** [mj1618/serverless-offline-sns#141]
Hello, I am using Serverless with typscript and the plugin is not working. I'm getting the following error:

`Class extends value [object Object] is not a constructor or null`

Do you know what this could possible be? My current config is:

`"serverless-offline-sns": {
      port: 4002,
      debug: true,
      location: ".webpack"
    }`

Thank you.

**Comment by richlloydmiles** [comment]
Hi,

It is unlikely the plugin is causing this issue as all it is doing is with regards to typescript is setting the location of the handler.js file - https://github.com/mj1618/serverless-offline-sns/commit/746b5581c185768c96a7aa09012a977983be2cb0#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

I assume in your case the handler.js file is found in `.webpack/handler.js` ?

Additionally, it seems like that particular error is introduced when there is a circular dependency or when something is exported incorrectly.

**Comment by Bemjamin** [comment]
The error happens before it touches this line. It happens when it requires sls-config-parser:

`var sls_config_parser_1 = require("./sls-config-parser");`

**Comment by evandromillian** [comment]
I received the same error with the newest version (0.76.0 at this time). 
When I executed the example project serverless-offline-sns-example, the version used was 0.72.0. The older version works correctly.

**Comment by qstyler** [comment]
Sadly it was an issue https://github.com/mj1618/serverless-offline-sns-example/issues/1
and this plugin still cannot handle typescript property

I'm using `nx` with `@ns3/nx-serverless` and it works just fine unless I try to do something with SNS.

Then it gives me all possible errors whatever I try to do...

**Comment by jhonpedro** [comment]
Works fine if your serverless config file is a yml.

Here is an [example](https://github.com/jhonpedro/sls-sns-notifications).

**Comment by rcambrj** [comment]
This appears to have broken somewhere between `0.74.0..0.75.0`

**Comment by gusbernardo** [comment]
I'm running into the same issue, is there a work around for this?

**Comment by newtechfellas** [comment]
> I'm running into the same issue, is there a work around for this?

I reverted to 0.74.0 as work around as per [above](https://github.com/mj1618/serverless-offline-sns/issues/141#issuecomment-1057157346) comment

**Comment by bhalani97** [comment]
As mentioned by @evandromillian version 0.72 works.
Thanks

**Comment by dsarlo** [comment]
Does this work with version 0.77.0+? If not, can someone provide a reproducer?

**Comment by dsarlo** [comment]
Tested using the example project with the latest version 0.77.1 and it works with a ts serverless definition. Closing!
