### ISSUE TITLE
SNS cannot handle special characters in its message

### ISSUE THREAD

**Issue by jadehwangsonos** [mj1618/serverless-offline-sns#15]
Hi again,

It's me again. :)
I found that SNS message cannot handle special characters. 

**[What works]**
`sns.publish({
    Message: "hello! ",
    MessageStructure: "json",
    TopicArn: "arn:aws:sns:us-east-1:123456789012:test-topic",
  }
`

**[What NOT work]**
`sns.publish({
    Message: "hello! Porée",
    MessageStructure: "json",
    TopicArn: "arn:aws:sns:us-east-1:123456789012:test-topic",
  }
`
Is this something you can support? 

Thanks!

**Comment by mj1618** [comment]
Cool yes I should be able to fix this

**Comment by mj1618** [comment]
Try v0.29 it should work now 😉
