### ISSUE TITLE
Publish message to offline sns server with aws cli?

### ISSUE THREAD

**Issue by ezmiller** [mj1618/serverless-offline-sns#152]
Is it possible to publish to the offline sns server using the aws cli command, i.e. `aws sns publish`?

**Comment by ormu5** [comment]
Yes. It might look something like

```aws --endpoint-url http://localhost:4002 sns publish --topic-arn arn:aws:sns:us-east-1:123456789012:my-example-topic-v1-local --message file://./sample-data/my-sample-payload.json```

while 
```aws --endpoint-url http://localhost:4002 sns list-topics```

lists available topics.
