### ISSUE TITLE
Does not work with .mjs extension

### ISSUE THREAD

**Issue by fzanfolim** [mj1618/serverless-offline-sns#160]
I'm using esbuild to generate lambda in mjs extension, but when running sns offline, Error: Cannot find module.
Any suggestion

**Comment by dsarlo** [comment]
@fzanfolim This should work now. The project has been converted to an esmodule

**Comment by mattkindy** [comment]
It does not. If one outputs `.mjs` files for the handlers (e.g. in order for [AWS Lambda ESM support](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/) without package.json), it errors. You can see `.js` is hardcoded here:
https://github.com/mj1618/serverless-offline-sns/blob/c15b24a19927f760dd5a486efd1bf7374ec207b6/src/index.ts#L507

Here is a patch if you use `patch-package` to get around this for now.

```patch
diff --git a/dist/index.js b/dist/index.js
index ad535e76b3f79e6f90ffdb0cbb50118b51906f53..0e7d5a2fc83e68427e1bb4c40da70048aa803146 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -411,7 +411,7 @@ class ServerlessOfflineSns {
         const handlerPath = fn.handler.substring(0, handlerFnNameIndex);
         const handlerFnName = fn.handler.substring(handlerFnNameIndex + 1);
         const fullHandlerPath = resolve(location, handlerPath);
-        const handlers = await import(`${url.pathToFileURL(fullHandlerPath)}.js`);
+        const handlers = await import(`${url.pathToFileURL(fullHandlerPath)}.mjs`);
         return handlers[handlerFnName] || handlers.default[handlerFnName];
     }
     log(msg, prefix = "INFO[serverless-offline-sns]: ") {

```
