### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by FloUz-ai** [mj1618/serverless-offline-sns#175]
For any reason, the sns is trigger corrctly, but when it comes to start the function supposed to start. It seems that, it cannot find the handler. 

here a part of the error: 

``` DEBUG[serverless-offline-sns][server]: {"size":0,"timeout":0}
Error: Cannot find module '/Users/**/Documents/**/src/handlers/sns/fun'
Require stack:
- /Users/**/Documents/**/node_modules/serverless-offline-sns/dist/index.js
- /Users/**/Documents/**/node_modules/serverless/lib/utils/require-with-import-fallback.js
- /Users/**/Documents/**/node_modules/serverless/lib/classes/plugin-manager.js
- /Users/**/Documents/**/node_modules/serverless/lib/serverless.js
- /Users/**/Documents/**/node_modules/serverless/scripts/serverless.js
- /Users/**/Documents/**/node_modules/serverless/bin/serverless.js ```

Any idea what could be the issue?

**Comment by ashwini-fung** [comment]
> For any reason, the sns is trigger corrctly, but when it comes to start the function supposed to start. It seems that, it cannot find the handler.
> 
> here a part of the error:
> 
> ```
> Error: Cannot find module '/Users/**/Documents/**/src/handlers/sns/fun'
> Require stack:
> - /Users/**/Documents/**/node_modules/serverless-offline-sns/dist/index.js
> - /Users/**/Documents/**/node_modules/serverless/lib/utils/require-with-import-fallback.js
> - /Users/**/Documents/**/node_modules/serverless/lib/classes/plugin-manager.js
> - /Users/**/Documents/**/node_modules/serverless/lib/serverless.js
> - /Users/**/Documents/**/node_modules/serverless/scripts/serverless.js
> - /Users/**/Documents/**/node_modules/serverless/bin/serverless.js ```
> 
> Any idea what could be the issue?
> ```

Did you find any solution for this? @FloUz-ai
