### ISSUE TITLE
Environment variable priority

### ISSUE THREAD

**Issue by MajorCaiger** [mj1618/serverless-offline-sns#177]
Hi

We noticed that the priority of environment variable source is different in serverless-offline-sns compared to serverless-offline. 

serverless-offline merges in the following order:

process.env
provider.env
function.env

serverless-offline-sns merges in this order:

provider.env
process.env
function.env

I've raised a PR to tweak the order to match serverless-offline

https://github.com/mj1618/serverless-offline-sns/pull/176

Thanks

**Comment by dsarlo** [comment]
Closing - will take a look at the PR #176
