### ISSUE TITLE
Environment variables not set in handler function

### ISSUE THREAD

**Issue by jamiel** [mj1618/serverless-offline-sns#18]
When calling a serverless handler function through the sns event on the serverless-offline-sns plugin endpoint, the environment variables defined in serverless.yaml are not present in process.env . They are present when going through the the API gateway on serverless-offline so this problem seems to be isolated to the serverless-offline-sns plugin.

**Comment by mj1618** [comment]
Yep you’re right - I’m able to reproduce. Thanks I will look into this shortly.

**Comment by mj1618** [comment]
Actually not sure I can reproduce the error now... I have written a fix but I don't seem to have been able to produce the original error.

Can you please share your code (the relevant parts)? Or recreate the issue using https://github.com/mj1618/serverless-offline-sns-example

**Comment by mj1618** [comment]
I've tried to recreate it here - https://github.com/mj1618/serverless-offline-sns-example/tree/env_var_issue

But when I use `npm start` and hit localhost:3000/ping it does in fact show me the correct env var in the console logs.

**Comment by jamiel** [comment]
Thanks for looking into this. I believe in your example it works because the SNS handler is sharing the same process as the API gateway, and when you use the API gateway for the ping serverless-offline process.env gets updated correctly and then the pong handler is loaded afterwards. To reproduce make a test file on your branch, say test.js with just the SNS publish code, then restart serverless-offline and run test.js rather than calling /ping through the http handler and you will see the issue. I believe I'm having this issue because I don't use API gateway, I'm just using SNS handlers. My test.js is below:

```
use strict';
var AWS = require("aws-sdk");
var sns = new AWS.SNS({
  endpoint: "http://127.0.0.1:4002",
  region: "us-east-1",
});

sns.publish({
  Message: "hello!",
  MessageStructure: "json",
  TopicArn: "arn:aws:sns:us-east-1:123456789012:test-topic",
}, () => {
  console.log("ping");
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Ping sent!',
    }),
  };
});
```

**Comment by mj1618** [comment]
Gotcha, thanks I'll give it a go.

**Comment by mj1618** [comment]
Here's what I'm doing on this branch -https://github.com/mj1618/serverless-offline-sns-example/tree/env_var_issue

1. `serverless offline start`
2. `node ./test.js`

I still get the right env variable showing. 

Sorry if I've misunderstood the use case

**Comment by mj1618** [comment]
Wait... silly me I was using the code with the fix applied. Ok turning the fix off I can reproduce the error.

**Comment by mj1618** [comment]
Publishing v0.32.0 with the fix in it.

**Comment by mj1618** [comment]
Yep you can take a look now with v0.32 - let me know if there's still any issues.

**Comment by jamiel** [comment]
Brilliant, that works now thanks @mj1618 . Much appreciated.
