### ISSUE TITLE
[Bug]: npm version is not up to date. autoSubscribe flag on main but not on npm

### ISSUE THREAD

**Issue by MichalOleszczuk** [mj1618/serverless-offline-sns#180]
### Bug description
There is code difference between repository/main and what is available on [npm (Last published 2 years ago)](https://www.npmjs.com/package/serverless-offline-sns)

### Environment
- Windows 10
- Node version: 16.20.0
- NPM version: 8.19.4
- package.json "serverless-offline-sns": "0.76.0",

### Bugfix or workaround
Bump [version of package in package.json](https://github.com/mj1618/serverless-offline-sns/blob/main/package.json#L3) and allow github action to publish new version to NPM.

### Impact
This issue makes SNS -> SQS subscription (Resource) not possible with use of localstack since flag `autoSubscribe` is not present in code on npm.
This will not work:
```typescript
      'serverless-offline-sns': {
        'sns-endpoint': 'http://localhost:4566',
        accountId: process.env.AWS_ACCOUNT_ID,
        debug: true,
        autoSubscribe: false,
        subscriptions: [
          {
            topic: {
              topicName: 'synchronize-profile-email-topic',
              rawMessageDelivery: 'true',
            },
            queue: `arn:aws:sqs:${process.env.AWS_DEFAULT_REGION}:${process.env.AWS_ACCOUNT_ID}:synchronize-profile-email`
          }
        ],
      }
    [...]
      SnsSynchronizeProfileEmailSubscription: {
        Type: 'AWS::SNS::Subscription',
        Properties: {
          Protocol: 'sqs',
          Endpoint: { 'Fn::GetAtt': ['SynchronizeProfileEmailQueue', 'Arn'] },
          TopicArn: { Ref: 'SnsSynchronizeProfileEmailTopic' },
          RawMessageDelivery: 'true',
        },
      },
```

### Details
Repository code contains new features like [autoSubscribe flag](https://github.com/mj1618/serverless-offline-sns/blob/main/src/index.ts#L207) that is present in repository but not available in npm package bundle.
![2](https://user-images.githubusercontent.com/20791723/231695626-9e989c61-e479-4348-80ff-9ef159fd9183.png)
vs
![1](https://user-images.githubusercontent.com/20791723/231693459-d6c86f31-af94-46ac-b242-0775156e1dec.png)

**Comment by MichalOleszczuk** [comment]
@mj1618  - Will npm pipeline pick it automatically if I do PR?

**Comment by dsarlo** [comment]
@MichalOleszczuk This should be resolved. Will reopen if you're still having issues
