### ISSUE TITLE
Issue when running inside Node v18.16.1

### ISSUE THREAD

**Issue by nicholas-yong** [mj1618/serverless-offline-sns#183]
Hi all, I ran into an error running `serverless` locally after upgrading my severless template to support a runtime of `nodejs18.x`.

When attempting to send a SNS message locally, I get this error below ->

```
Error publishing in SNS: || {"msg":"UnknownEndpoint: Inaccessible host: `localhost' at port `4002'. This service may not be available in the `ap-southeast-2' region.","stack":"UnknownEndpoint: Inaccessible host: `localhost' at port `4002'. This service may not be available in the `ap-southeast-2' region.
```

I found [this](https://stackoverflow.com/questions/71799147/serverless-offline-dynamodb-throws-local-unknownendpoint-inaccessible-host-l) that makes me think its related to the version upgrade, but I am not 100% sure.

**Comment by juancarlosDH** [comment]
Hi Nico!
Can you resolve this error?
Are you using docker?

**Comment by dsarlo** [comment]
@juancarlosDH @nicholas-yong We have pushed a new version v0.77.0. Can one of ya'll verify you're still having the issue? I am running 18.17.1 and it works fine here.
