### ISSUE TITLE
CommonJs imports broken

### ISSUE THREAD

**Issue by renejesusgv** [mj1618/serverless-offline-sns#191]
With the latest release, handlers in CommonJS module syntax can't be returned properly by the `createJavascriptHandler` function anymore, resulting in a `TypeError: getHandler is not a function`  error. With  Webpack dynamic imports, sometimes the exported function is under the `default` property. Doing something like this seems to fix the issue:

```
async createJavascriptHandler(fn, location) {
        // Options are passed from the command line in the options parameter
        this.debug(process.cwd());
        const handlerFnNameIndex = fn.handler.lastIndexOf('.');
        const handlerPath = fn.handler.substring(0, handlerFnNameIndex);
        const handlerFnName = fn.handler.substring(handlerFnNameIndex + 1);
        const fullHandlerPath = resolve(location, handlerPath);
        const handlers = await import(`${url.pathToFileURL(fullHandlerPath)}.js`);
        return handlers[handlerFnName] || handlers.default[handlerFnName]; // if the handler is undefined then look for the function in the default property. 
    }
```

**Comment by dsarlo** [comment]
@renejesusgv Could you please provide me with a basic reproducer for this to test? I’ll take a swing at it this weekend if I have some time otherwise. Thanks for bringing this to my attention! Appreciate the help here!

**Comment by dsarlo** [comment]
See: https://github.com/mj1618/serverless-offline-sns/releases/tag/0.77.2
