### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by edtan-caseware** [mj1618/serverless-offline-sns#201]
Hello,

Thanks for this project!  Wondering if you could cut a new release?  I was interested in getting this https://github.com/mj1618/serverless-offline-sns/issues/194, but it doesn't look like it's in the latest available release (0.77.2).

Thanks!
Ed

**Comment by dsarlo** [comment]
@edtan-caseware Sorry for the wait. Totally slipped my mind after work - https://github.com/mj1618/serverless-offline-sns/releases/tag/0.78.0

Version 0.78.0 has been released!

**Comment by edtan-caseware** [comment]
No problem, thanks so much!!
