### ISSUE TITLE
localstack:stable is not publishing SNS messages due to subscription confirmation HTTP requests not sending a response 

### ISSUE THREAD

**Issue by anaerobic** [mj1618/serverless-offline-sns#211]
when localstack sends the subscription confirmation request we are fetching the `SubscribeURL` to enable the subscription at https://github.com/mj1618/serverless-offline-sns/blob/b2987bd231f991be4a770869b1c978ad7df41ebc/src/sns-adapter.ts#L152 but we are not subsequently completing that subscription confirmation request, which looks to be exhausting the localstack HTTP connection pool with a sufficiently large number of SNS subscriptions.

**Comment by dsarlo** [comment]
@anaerobic cut release [0.78.1](https://github.com/mj1618/serverless-offline-sns/tree/refs/tags/v0.78.1)
