### ISSUE TITLE
Custom aws endpoint is not working correcly due to wrong subscriptionEndpoint

### ISSUE THREAD

**Issue by reneeichhorn** [mj1618/serverless-offline-sns#23]
**Current behavior:**
When using the internal SNS server, a subscription call will also create a new route `{endpoint}/{lambda-function-name}` this route will be used a `subscriptionEndpoint` then.
For a custom aws endpoint though the `subscriptionEndpoint` is also `{endpoint}/{lambda-function-name}` and of course for localstack sns this is an unknown route.

**Expected behavior:**
The subscription endpoint should be configurable and/or use the `serverless-offline` endpoint.

**Comment by mj1618** [comment]
Thanks @reneeichhorn I’ll take a look

**Comment by mj1618** [comment]
Alright should be good if you try v0.35.

An example use (with localstack SNS) I've made available on this branch - https://github.com/mj1618/serverless-offline-sns-example/tree/custom-endpoint
