### ISSUE TITLE
Support other stacks (i.e.: python)

### ISSUE THREAD

**Issue by HoneyryderChuck** [mj1618/serverless-offline-sns#25]
I'm looking for the equivalent plugin for python, but haven't been able to. 

On an experimental note: how hard would it be to support stacks other than node? The way I see it, the runtime is declared in the serverless.yml (provider.runtime), and one could just fork-exec a call to the method (?)

**Comment by mj1618** [comment]
Hey there!

So if you listen on a HTTP endpoint you can use this plugin as it is with python. This plugin will send requests to any HTTP endpoint.

If you want to call directly to python with it I'm not quite sure how it would work. Does serverless work with python?

**Comment by HoneyryderChuck** [comment]
> So if you listen on a HTTP endpoint you can use this plugin as it is with python. This plugin will send requests to any HTTP endpoint.

What do you mean by that?

> Does serverless work with python?

Yes. In dev, I'm using [serverless-wsgi](https://github.com/logandk/serverless-wsgi) for the http endpoints. I'm now setting up a function which will trigger over SNS, but I'm not able to use it in dev. Was hoping that this lib could help.

The way I see it, [one could rewrite this part](https://github.com/mj1618/serverless-offline-sns/blob/master/src/index.ts#L141-L142) to do an exec syscall and call the function in a child process, but I might be wrong here.

**Comment by mj1618** [comment]
Yea so what I mean is you can:
- startup serverless offline sns
- use AWS python lib to subscribe with a HTTP endpoint (pointing to your python app)
- use AWS python to send an event
- that event will be sent to the HTTP endpoint

But yes - exec syscall will work, I just don’t know how wsgi works, when you use exec is there any state that needs to be passed through?

Feel free to give it a crack and submit a PR, always happy to add new features

**Comment by HoneyryderChuck** [comment]
this might be more complicated than just fork+exec, because you actually need to pass the arguments to a function, and that's difficult to guarantee under these conditions. Maybe this is not achievable using serverless...
