### ISSUE TITLE
Function won't fire - Unclear documentation of required ARN topic format

### ISSUE THREAD

**Issue by kensykora** [mj1618/serverless-offline-sns#26]
I had this same issue as #24 (by @Siyfion) and had to dig in to figure out what the issue was. The documentation isn't 100% clear on this, but your code sample and some source code inspection confirmed it, **when you publish a message you HAVE to use an ARN containing the Amazon account ID** `123456789012`.

e.g., format of `TopicArn` must be equal to `arn:aws:sns:us-east-2:123456789012:TopicName`

I was trying to publish to topic "TopicName" and not including a fully formatted ARN (Since it didn't make sense in the context of a local SNS... what would the region / account ID be?). 

Requests:

1. Update readme to be clear that the published topic MUST match this format
2. Have a warning show up in the serverless offline console when it received a message that it couldn't handle, and possibly list the available topics that it can process to aid diagnosing this issue
3. Alternatively, it would be nice to removed the need for a fully qualified ARN entirely since the SNS client library itself doesn't require a fully qualified ARN (at least the `aws-sdk` NPM client does not) -- e.g., allow the client to send to `TopicArn: "TopicName"` instead of `TopicArn: "arn:aws:sns:us-east-2:123456789012:TopicName"`

**Comment by sahalsaad** [comment]
You can see the arn if you enable the [debug](https://github.com/mj1618/serverless-offline-sns#installation). `debug: true`

**Comment by byF** [comment]
@kensykora You can change the account id through config:
```yaml
custom:
  serverless-offline-sns:
    accountId: WHATEVER_HERE
```

**Comment by shierro** [comment]
in my case, following the 1st example on the [official docs](https://serverless.com/framework/docs/providers/aws/events/sns#using-a-pre-existing-topic)
```
someNiceFunction:
    events:
      - sns: arn:aws:sns:ap-southeast-2:13135XXXXXXXXX:update-user-prod
```
Does not trigger the subscribed function.

following the 2nd convention on the official docs, is the one that works
```
someNiceFunction:
    events:
      - sns:
          arn: arn:aws:sns:ap-southeast-2:13135XXXXXXXXX:update-user-prod
```

Would you consider supporting the 1st one, or as suggested earlier improve documentation to note that 1st option from the docs is not yet supported?

**Comment by jkruse14** [comment]
Following up on @shierro's comment, if the snsConfig is a string, the plugin assumes this is the topicName, but Serverless docs require this to be the ARN:

<img width="849" alt="offline-sns-issue" src="https://user-images.githubusercontent.com/16331726/53194180-64b06280-35d8-11e9-9081-0d159882873c.png">

Here you can see the docs show it as the ARN and you will actually get an error when trying to deploy if this is not set correctly:
https://serverless.com/framework/docs/providers/aws/events/sns#using-a-pre-existing-topic

**Comment by mj1618** [comment]
Sorry for the delay all, this should be fixed after the merge.
