### ISSUE TITLE
Dynamodb offline

### ISSUE THREAD

**Issue by eladhaz05** [mj1618/serverless-offline-sns#3]
Is there an option to use dynamodb offline plugin with it?

**Comment by mj1618** [comment]
Do you mean from a Dynamo stream?

Also which plugin are you referring to, is it this one? https://www.npmjs.com/package/serverless-dynamodb-local

**Comment by eladhaz05** [comment]
Yes, this one.
I want that when a function is called by the offline-sns it also will recognize my migrations with this plugin.
I try it and it did not work.
Thank you

**Comment by mj1618** [comment]
Sorry but I'm not exactly sure the use-case.

Are you trying to listen on a Dynamo stream? e.g. http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.html

**Comment by mj1618** [comment]
Can you provide some sample code to demonstrate the use case?

**Comment by eladhaz05** [comment]
For example:
I run two services with serverless-oflline with different ports
One of them uses serverless-offline-sns plugin with a different port.
Two of them use dynamodb-local plugin also with different ports.
When I try to call one service to another using SNS, everything works fine until I try to query something from the dynamodb that i use locally with dynamodb-local plugin.
It always said that I did not do migrations.

**Comment by mj1618** [comment]
Hi @eladhaz05 

It seems to work fine for me, here's an example: https://github.com/mj1618/serverless-offline-sns-example/tree/dev/dynamo-local

**Comment by eladhaz05** [comment]
Thank you,
I checked again works fine.
