### ISSUE TITLE
Message with default or not

### ISSUE THREAD

**Issue by bargenson** [mj1618/serverless-offline-sns#37]
I started to develop a project locally using serverless-offline-sns and I realized once I deployed on AWS that published messages that were working locally didn't work then.
SNS requires messages to have a top-level `default` key. The subscriber then receives the content of the default key directly.
Locally though, the subscriber seems to not receive the same thing than on AWS but exactly the same message as the one published with the top-level default key.
I would expect to have the same behaviour with serverless-offline-sns than with AWS SNS...

Did I do something wrong or is it a bug ?

**Comment by all9lives** [comment]
I experienced the same issue, it would be great if this plugin mimicked the aws behavior of requiring the top-level `default` key and passing that down as the message when the notification is being received.

**Comment by eduardrock** [comment]
I got the same problem.
Why does it require a default key on the JSON message but on the documentation they use the value "hello!"?. 
I doesn't make sense.

![image](https://user-images.githubusercontent.com/1775903/88436645-adbea480-cdd2-11ea-9e37-622e5039b126.png)
