### ISSUE TITLE
serverless-offline-sns does not start when using serverless-offline

### ISSUE THREAD

**Issue by dboune** [mj1618/serverless-offline-sns#50]
Using the following packages, serverless-offline-sns does not start when running `serverless offline`

```
├─ serverless-offline-sns@0.49.0
├─ serverless-offline@3.32.2
├─ serverless@1.36.0
```

It does start just fine when running `serverless offline-sns start`.

Quickly messing about, and using another working plugin as example, I was able to get it to start by making the following change in the dist package... note the addition of a `before:offline:start` hook.

```
this.hooks = {
            "before:offline:start:init": function () { return _this.start(); },
            "before:offline:start": function () { return _this.start(); },
            "after:offline:start:end": function () { return _this.stop(); },
}
```

**Comment by dboune** [comment]
I've learned this is due to a difference between running `serverless offline start` and `serverless offline` (without `start`). For whatever reason most packages (including serverless-webpack) add "before:offline:start" so that the package will function either way.

**Comment by dpickett** [comment]
@dboune thanks for that tip. my publish invocations were timing out and I had no visibility into what's happening. Running `sls offline start` explicitly eliminates the issue for me.

**Comment by MarcelCutts** [comment]
I lost a lot of time hunting this down. I'll put it in the README.
