### ISSUE TITLE
AWS_LAMBDA_ environment variables not set when handler called

### ISSUE THREAD

**Issue by dboune** [mj1618/serverless-offline-sns#51]
When a function is called that publishes an SNS message to a queue, the receiving function does not have the AWS_LAMBDA_* environment variables set. These variables are set properly for the calling function.

In a plain serverless local invocation these are set by the AwsInvokeLocal plugin. https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L102-L110

**Comment by dboune** [comment]
Also noticed that IS_LOCAL isn't propagated either, but IS_OFFLINE is available.

**Comment by mj1618** [comment]
Cool thanks for the info, any suggestions how to fix this?
