### ISSUE TITLE
Commit has broken the library

### ISSUE THREAD

**Issue by gevorggalstyan** [mj1618/serverless-offline-sns#61]
Commit dcd774a82902e0b56ce96673b3286ef6b7b1a8c0 has broken the library making entirelly incorrect assumption.

The comment in the code says "According to Serverless docs, if the sns config is a string, that string must be the topic ARN. https://serverless.com/framework/docs/providers/aws/events/sns#using-a-pre-existing-topic".

The commit is misinterpreting the documentation. There is nothing on that page that would lead to the changes in the code from the commit. AWS SNS documentation itself does not lead to any changes like this (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html).

The changes need to be reverted as soon as possible as they are breaking the code. To make sure, just use the first example from the same documentation page and see that SNS topic is not created because of snsConfig.indexOf("arn:aws:sns") === 0.

Meanwhile v0.49 is the latest version that actually works.

**Comment by juancarlosfarah** [comment]
I don't know if it's related, but I'm seeing that if I use the following syntax, the event does not get called correctly when `topic-name` is published.

```
events:
  - sns: topic-name
```

However, the `arn` syntax does work.

```
events:
    - sns:
        arn: arn:aws:sns:...
```

As indicated by @gevorggalstyan everything works well on v0.49.

**Comment by MatissJanis** [comment]
This works:
```yaml
events:
  - sns:
      topicName: topic-name
```

**Comment by gevorggalstyan** [comment]
@MatissJanis nice observation, that means we also have an inconsistency in the approach and the way how serverless treats both of these ways equally.

@mj1618 could you please revert that commit? We would really love to use later versions of the plugin.

**Comment by mj1618** [comment]
Pushing a fix now, apologies for the delay
