### ISSUE TITLE
Body inconsistency when used with SQS

### ISSUE THREAD

**Issue by Clement134** [mj1618/serverless-offline-sns#62]
The body received after publishing in an SQS queue from an SNS topic is different between local and cloud executions.

I have a lambda function which publishes a message on an SNS topic linked with an SQS queue. Another lambda gets messages from this queue and logs it.

With local execution body of received messages has the following structure:
```json
{
    "Records": [{
        "EventVersion":"1.0",
        "EventSubscriptionArn":"arn:aws:sns:region:id:sns-topic",
        "EventSource":"aws:sns",
        "Sns":{
            "SignatureVersion":"1",
            "Timestamp":"2019-03-10T08:23:15.303Z",
            "Signature":"EXAMPLE",
            "SigningCertUrl":"EXAMPLE",
            "MessageId":"22792a31-0532-4fca-829c-4c6db1990b9b",
            "Message":"Test message",
            "MessageAttributes":{},
            "Type":"Notification",
            "UnsubscribeUrl":"EXAMPLE",
            "TopicArn":"arn:aws:sns:region:id:sns-topic"
        }
    }]
}
```
But on AWS, the body has this structure:
```json
{
    "Type" : "Notification",
    "MessageId" : "9737c96d-41fa-505e-a6e4-9d9395d139d7",
    "TopicArn" : "arn:aws:sns:region:id:sns-topic",
    "Message" : "Test message",
    "Timestamp" : "2019-03-10T08:59:23.398Z",
    "SignatureVersion" : "1",
    "Signature" : "Signature",
    "SigningCertURL" : "SigningCertURL",
    "UnsubscribeURL" : "UnsubscribeURL"
}
```

The main and most problematic difference is the useless wrapping in the `Records` array. This forces the use of specific treatment for offline use which is not very recommended.

**Comment by mj1618** [comment]
Can you please see if this is still happening? I think it should be fixed now
