### ISSUE TITLE
filterPolicy doesn't check the values of every filter, only that the keys have a value provided and one value matches

### ISSUE THREAD

**Issue by mteleskycmp** [mj1618/serverless-offline-sns#66]
I have a block similar to this in my `serverless.yml` file

    consumeSNS:
      handler: src/functions/sns/consume.handler
      events:
        - sns:
            arn: "arn:aws:sns:us-east-1:123456789012:event_storage_topic"
            filterPolicy:
              name:
                - user.created
                - user.updated
              origin:
                - component1
              version:
                - '1.0.0'

My expected logic for this would be that the `consume.handler` would only receive the event from SNS if: `(name == user.created || user.updated) && origin = component1 && version = '1.0.0')`

However, the way the logic in `SNSServer.prototype.evaluatePolicies` works it will receive the event as long as ONE of those is true.

I haven't gotten to production with this deployment yet, and am not sure exactly how this is handled in Cloudformation, but from the documentation in the AWS SDK (https://docs.aws.amazon.com/sns/latest/dg/message-filtering-apply.html) they should all be required to be true.

Anyone have ideas on this? Am I wrong in how Cloudformation works or does this module need fixing?

**Comment by mteleskycmp** [comment]
While modifying the tests to verify this is an issue I realize that the tests miss this case:
 - Property exists on the event, but value is wrong

In the test `should not send event when multiple filter policies exist and the message only satisfies one` the second value in the event isn't set and the check in `EvaluatePolicies` does successfully break if the filter isn't provided. However, it misses the case where the value is provided, but it is just wrong.

**Comment by mteleskycmp** [comment]
I made a pull request to fix it https://github.com/mj1618/serverless-offline-sns/pull/67

**Comment by mj1618** [comment]
Merged, let me know if this works. Apologies for the delay in response.
