### ISSUE TITLE
Adding this plugin in serverless.yml breaks API Gateway Handler

### ISSUE THREAD

**Issue by sagarpatke** [mj1618/serverless-offline-sns#69]
Steps to reproduce:
In a working serverless project:
1. Install: `npm install -D serverless-offline-sns`
2. Add serverless-offline-sns to plugins in serverless.yml
3. run `npm offline start`
4. curl the API Gateway route, fails with the below error message
5. comment the plugin in serverless.yml, functionality starts to work again

The error displayed:
{"message":"The security token included in the request is invalid.","code":"UnrecognizedClientException","time":"2019-04-23T09:33:15.640Z","requestId":"fc5da850-64db-8786-a965-761720a08619","statusCode":400,"retryable":false,"retryDelay":63.06871720931615}

**Comment by mj1618** [comment]
Weird, looks like an AWS credentials issue. Does configuring AWS creds help?
