### ISSUE TITLE
Reading skipCacheInvalidation option from the wrong place

### ISSUE THREAD

**Issue by victorsferreira** [mj1618/serverless-offline-sns#71]
https://github.com/mj1618/serverless-offline-sns/blob/efe0e954fdd647f7bab72b52bf231399ca368e8a/src/index.ts#L180

The condition in this line is never satisfied if we pass `skipCacheInvalidation` from the command line.

Launching the application as following:

`serverless offline --skipCacheInvalidation start`

Will keep the parameters stored in the `this.options` object.

So, replacing `this.serverless.config.skipCacheInvalidation` with `this.options.skipCacheInvalidation` would make it work.

Is there other ways to pass `skipCacheInvalidation` to SNS? 

what do you think about it?

**Comment by mj1618** [comment]
Looks good, thank you for the PR!
