### ISSUE TITLE
RawMessageDelivery with SQS

### ISSUE THREAD

**Issue by jodybrazil** [mj1618/serverless-offline-sns#74]
Subscribing the SNS queue to an SQS queue with the attribute `RawMessageDelivery="true"` will cause exception:

```
TypeError: Cannot read property 'map' of undefined
    at SNSServer.publishSqs (/Users/jbrazil/dev/dOps/neo-backend/src/services/task-manager/node_modules/serverless-offline-sns/dist/sns-server.js:190:39)
    at /Users/jbrazil/dev/dOps/neo-backend/src/services/task-manager/node_modules/serverless-offline-sns/dist/sns-server.js:225:30
    at Array.map (<anonymous>)
    at SNSServer.publish (/Users/jbrazil/dev/dOps/neo-backend/src/services/task-manager/node_modules/serverless-offline-sns/dist/sns-server.js:203:101)
```

This is caused by `event` being set to the value of message at: https://github.com/mj1618/serverless-offline-sns/blob/master/src/sns-server.ts#L239

A simple fix to this could be to replace that block with:

```
            if (sub["Attributes"]["RawMessageDelivery"] === "true") {
                const record = { Records: [{ Sns: JSON.parse(message) }] };
                event = JSON.stringify(record);
            }
```

**Comment by pjcav** [comment]
Created this PR for the issue.  https://github.com/mj1618/serverless-offline-sns/pull/75.  just sending the message along if RawMessageDelivery is set

**Comment by mj1618** [comment]
Merged, let me know if you still experience issues

**Comment by rubesMN** [comment]
This issue is happening again in 0.65.0.

**Comment by ing-mar-ef** [comment]
Issue still there in v0.68.0. As far as I could see, sub["Attributes"]["RawMessageDelivery"] === "true") is false because Attributes property is {}.
This is quite a big issue and it prevent from testing sns+sqs scenarios.

**Comment by harryhazza77** [comment]
yes still in issue in v0.68.0
