### ISSUE TITLE
Support for Webpack

### ISSUE THREAD

**Issue by todda00** [mj1618/serverless-offline-sns#8]
Is there anyway the subscribed function can be called using the webpack compiled code? Currently I am using serverless-offline and serverless-webpack which work great, but when I publish to the SNS topic subscribed by serverless-offline-sns, the handler function fails since its not using the webpack version:
```
import fetch from 'node-fetch';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by mj1618** [comment]
Hi @todda00 

Yea this sounds like it should work.

I might try and reproduce your issue first, any info/config you can provide to help me would be much appreciated.

Note that although this plugin is written in typescript, the compiled+packaged code is base es6 without any import keywords. So you must have cloned this plugin and are referencing the src/ directory?

**Comment by todda00** [comment]
Your package isn't including the src, the issue is with the handler that is being called after an SNS is published. The handler is being called directly, not pointing to the webpack compiled version. I modified your example to show the issue: https://github.com/todda00/serverless-offline-sns-example

You can see that the ping works fine and you could use any ES6 syntax you have configured with webpack. The pong function is what is being called without compiling to webpack. 

The issue it seems is that this line is looking for the handler in the source: https://github.com/mj1618/serverless-offline-sns/blob/master/src/index.ts#L118

But it needs to be checking for webpack output, which in this configuration is at `.webpack/service/handler.js`, not `handler.js` (relative to project root)

If there is a way to handle zero-config support for webpack, that would be great, but if not I see a viable solution would be to expose an option to specify the handler output in the serverless.yml file, something like: 

```
custom:
  serverless-offline-sns:
    output: .webpack/service
```

Which would then look for the handlers at that specified location instead of the project root

**Comment by mj1618** [comment]
Awesome great info there. I’ll take a look. I thought I was doing what serverless-offline does to look up handlers, I must have missed something.

**Comment by mj1618** [comment]
Hey there,

All fixed, I checked serverless offline and it uses the "location" option, so I just tapped into that to get it to work. https://github.com/mj1618/serverless-offline-sns/commit/fa0028d17e16b51a2a0b336c08610867bc97bf15

Let me know if it fixes the issue, you'll need to use v0.24

**Comment by mj1618** [comment]
Will leave the issue open until you confirm.

**Comment by todda00** [comment]
Updated the example repo to 0.24 and the same issue still persists: https://github.com/todda00/serverless-offline-sns-example

With debug enabled, the line here still prints the source version: https://github.com/mj1618/serverless-offline-sns/blob/fa0028d17e16b51a2a0b336c08610867bc97bf15/src/index.ts#L121

`require(/Users/toddhumphrey/Repos/serverless-offline-sns-example/./handler)[pong]`

**Comment by todda00** [comment]
This is where serverless-webpack is setting the location: https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/prepareOfflineInvoke.js

Which gets called before `serverless offline start`: 
https://github.com/serverless-heaven/serverless-webpack/blob/5c9f14d53f4ce739ebcf69748d532c0f5253b7c3/index.js#L130-L138

Not sure why the location serverless-offline-sns is getting ins't the webpack modified one.

**Comment by todda00** [comment]
Figured it out, the way the plugins are listed in serverless.yml matters, when I list them as follows all is well:

```
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns
```

I'm sure the location also still had to change for this to work, but with the correct plugin order, its using the webpack modified location now.

**Comment by mj1618** [comment]
Yea that’s right, it says that in the serverless offline documentation - I should put it in this projects readme as well.

Cheers

**Comment by krzkaczor** [comment]
@mj1618 you should definitely put it in readme :) I just started using your plugin and it didn't work but fortunately, I found this issue. Thanks!

**Comment by mj1618** [comment]
Oh right good feedback, will do!

**Comment by mj1618** [comment]
All done
