### ISSUE TITLE
--useSeparateProcesses

### ISSUE THREAD

**Issue by sean-hill** [mj1618/serverless-offline-sns#85]
Hey! This plugin is awesome. I'm just having a little issue where I have a persistent DB connection between lambda invocations. So on the second invocation I get an error saying my DB connection already exists. With `serverless-offline` they have a `--useSeperateProcesses` flag described [here](https://github.com/dherault/serverless-offline/blob/master/README.md#usage-and-command-line-options) that allows for seperate node process's to be run for each invocation. Is this possible with this plugin as well?

**Comment by mj1618** [comment]
I haven’t come across this or worked it out yet.

Is it possible to only create the connection if it doesnt already exist? Since a node process could be reused on subsequent lambda invocations in AWS anyway.

Otherwise any suggestions on how this feature could work?

**Comment by sean-hill** [comment]
I actually just removed the dependency I had causing this issue, so I'll close for now :)
