### ISSUE TITLE
functionName not the same as AWS

### ISSUE THREAD

**Issue by eladhaz05** [mj1618/serverless-offline-sns#9]
Hi,

Can you send in the context object the function name as it in AWS.
In you plugin it is just the name of the function,
In AWS it is "service name"-"stage"-"function name"
Will be very helpfull.

Thank you

**Comment by mj1618** [comment]
Hey @eladhaz05 sure I'm taking a look at this. Thanks!

**Comment by mj1618** [comment]
Hi @eladhaz05 try `v0.25.0`

In the example project I now get `sns-test-dev-pong` as the function name
