### ISSUE TITLE
Python runtime support

### ISSUE THREAD

**Issue by aniljaiswal** [mj1618/serverless-offline-sns#91]
I have a lambda function that should be invoked via SNS messages but the plugin is looking for js modules. 

Am I missing something or there is no support for Python 3 runtime yet?

**Comment by mj1618** [comment]
Sorry, currently it doesn't have support. I do accept pull requests though, or even a suggestion as to how to implement it would be useful.

**Comment by brentpabst** [comment]
@mj1618 Wonder if we can formulate an issue specifically to support non-JS runners.  Would ideally think we'd support the same runtimes as serverless-offline.  Looks like `node` `python` and `ruby` are invoked from the node runtime and compiled languages like `go` `java` `.net` are handled via container executions.  I personally would love to get `go` support working.  Imagine we could leverage a lot of the code in the base serverless-offline repo to handle this?

**Comment by AlysonBasilio** [comment]
@mj1618 did you tested https://github.com/mj1618/serverless-offline-sns/pull/102? I hava a lambda function in ruby that is not running and I think that Pull Request could solve this issue. It was merged but was not tagged.

**Comment by jeffster23** [comment]
I have had success using this plugin with Python 3.7 using the latest commit of this repo.

**Comment by pearsonhenri** [comment]
good tip, changing my package.json to 
```
"serverless-offline-sns": "git://github.com/mj1618/serverless-offline-sns#master"
```

got it done for me. any plans to release a new version of this package that includes that commit btw? :)

**Comment by ludwignyberg** [comment]
@mj1618 any updates on whether or not the latest commit will be released as a new package version?

**Comment by mj1618** [comment]
Sorry for the delay, new package versions are being released a bit more frequently now.

**Comment by uzair004** [comment]
Is it supported now ? in which version of serverless offline?
I am using `serverless-offline 7.x` & it doesn't work with python `3.6` but working with python `2.7`
