### ISSUE TITLE
The request entity too large where posting massage more than 100KB

### ISSUE THREAD

**Issue by stevencsf** [mj1618/serverless-offline-sns#92]
In AWS SNS server side the limited post message body is 10MB, but when in the offline have not a option to modify the size of body of the bodyParser using. 
Tried add limit of app use of bodyParser in index.js::58 
Form 
this.app.use(bodyParser.json({ type: ["application/json", "text/plain"]  })); 
To
this.app.use(bodyParser.json({ type: ["application/json", "text/plain"], limit:"10MB"  })); 

is not work. 

do the config of server provide this limit config? or should simulate as AWS limitation of the post and set the 10MB?

**Comment by mj1618** [comment]
Should be fixed, cheers
