### ISSUE TITLE
Multiple services sharing same SNS (localstack)

### ISSUE THREAD

**Issue by ricardovf** [mj1618/serverless-offline-sns#99]
Hi, thanks for this great plugin!

I have two services isolated, each with its serverless.yaml file. Im using localstack. I had to set the port differently for each service to make them work in parallel. I will be adding more services, so each will have to be on a different port, right? Is there a way to prevent this?

Also, the HOST IP ADDRESS (sns-subscribe-endpoint) has to be set for each computer, is there a way to use localhost or something?

Thanks!

Service A:
```
  serverless-offline-sns:
    port: 4003
    host: 0.0.0.0 # Enable plugin to listen on every local address
    sns-subscribe-endpoint: 192.168.0.107 # Host ip address
    sns-endpoint: http://localhost:4575 # Default localstack sns endpoint
    debug: true
    region: ${self:provider.region}
```

Service B:
```
  serverless-offline-sns:
    port: 4002
    host: 0.0.0.0 # Enable plugin to listen on every local address
    sns-subscribe-endpoint: 192.168.0.107 # Host ip address
    sns-endpoint: http://localhost:4575 # Default localstack sns endpoint
    debug: true
    region: ${self:provider.region}
```

**Comment by hakimio** [comment]
@ricardovf Did you find any workaround for host ip issue?

**Comment by ricardovf** [comment]
Nop, had to run each service on a different port

**Comment by ricardovf** [comment]
For the sns-subscribe-endpoint i did this:

sns-subscribe-endpoint: ${env:DEV_LOCAL_IP, 'host.docker.internal'} # Host ip address

On OSX no need for DEV_LOCAL_IP on the env, but on linux, yes.

**Comment by chasevida** [comment]
Just curious as to how you got them to publish across to each other. If Service A pushes an event via SNS was Service B picking up on it? I haven't yet got this working and seemed like you were doing something similar. Cheers.

**Comment by falecci** [comment]
What's the status on this? I've tried several configurations but I can't setup two services like @chasevida

**Comment by icameron** [comment]
@chasevida @falecci 

What worked for me was to setup a sls offline local sns service bridge

local-sns.yaml

```
service: local-sns
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
plugins:
  - serverless-offline-sns
  - serverless-offline
custom:
  serverless-offline-sns:
    port: 4002
    host: 0.0.0.0 
    debug: true
    accountId: 123456789012
```

then on the other services yamls
```
custom:
  serverless-offline-sns:
    port: 4005 #different port for each service 
    host: 0.0.0.0 # Enable plugin to listen on every local address
    sns-subscribe-endpoint: localhost
    sns-endpoint: http://localhost:4002 
```
